#!/usr/bin/env sh
set -eu
sh scripts/validate-blueprint.sh
sh scripts/authority-check.sh
sh scripts/preflight.sh
sh scripts/graph-validate.sh
sh scripts/source-evidence-check.sh
sh scripts/command-lock-check.sh
sh scripts/feature-coverage-check.sh
sh scripts/spec-trace-check.sh
sh scripts/source-coverage-check.sh
sh scripts/adapter-parity-check.sh
sh scripts/manifest-check.sh
sh scripts/placeholder-check.sh
sh scripts/format-check.sh
sh scripts/lint.sh
sh scripts/typecheck.sh
sh scripts/test-unit.sh
sh scripts/test-integration.sh
sh scripts/test-e2e.sh
sh scripts/build.sh
sh scripts/compatibility-gate.sh
sh scripts/security-check.sh
sh scripts/dependency-audit.sh
sh scripts/license-gate.sh
sh scripts/reality-gate.sh
sh scripts/performance-gate.sh
sh scripts/accessibility-gate.sh
sh scripts/platform-gate.sh
sh scripts/smoke-test.sh
sh scripts/live-fire.sh
echo 'verify: ok'
